spring.datasource.url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
spring.datasource.username: admin
spring.datasource.password: Nolisu111
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false