spring.datasource.url: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
spring.datasource.username: admin
spring.datasource.password: nolisu111
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

blog.MY_EMAIL: myjavamail441@gmail.com
blog.MY_PASSWORD: Admin111